services:
  compile-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: javac -cp .:src/ru/serjeypyzin/javacore/sample/Main.java src/ru/serjeypyzin/javacore/regular/*.java

  run-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: java -cp .:ru.serjeypyzin.javacore.sample.Main